# Generated by Django 4.2.3 on 2023-07-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
